import { useEffect, useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import customerService from '../../services/customerService';
import bookingService from '../../services/bookingService';
import paymentService from '../../services/paymentService';

// NOTE: This project simulates Razorpay instead of loading the real checkout.js
// widget, so there is no gateway-issued signature to send. The backend
// (BookingServiceImpl.verifySignature) independently recomputes
// HMAC-SHA256(orderId + "|" + paymentId) using razorpay.key-secret and rejects
// anything that doesn't match byte-for-byte, so the "sig_sim_..." placeholder
// that used to be sent here always failed with 400 Bad Request.
// This mirrors that same computation client-side so the mock flow succeeds.
// In a REAL integration, this secret must never live in frontend code — the
// real checkout.js widget returns a signature generated by Razorpay itself.
const MOCK_RAZORPAY_KEY_SECRET = 'mockSecret5678910';

async function computeMockRazorpaySignature(orderId, paymentId) {
  const encoder = new TextEncoder();
  const key = await window.crypto.subtle.importKey(
    'raw',
    encoder.encode(MOCK_RAZORPAY_KEY_SECRET),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign']
  );
  const signatureBuffer = await window.crypto.subtle.sign(
    'HMAC',
    key,
    encoder.encode(`${orderId}|${paymentId}`)
  );
  return Array.from(new Uint8Array(signatureBuffer))
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');
}

const BookCylinder = () => {
  const navigate = useNavigate();

  // Profile status check
  const [profile, setProfile] = useState(null);
  const [pageLoading, setPageLoading] = useState(true);

  // Form input states
  const [cylinderCount] = useState(1);
  
  // Checkout/Modal States
  const [bookingDetails, setBookingDetails] = useState(null);
  const [showPaymentModal, setShowPaymentModal] = useState(false);
  const [cardNumber, setCardNumber] = useState('');
  const [cardExpiry, setCardExpiry] = useState('');
  const [cardCvv, setCardCvv] = useState('');
  const [paymentMethod, setPaymentMethod] = useState('CARD'); // CARD, DEBIT_CARD, UPI, NETBANKING, WALLET
  const [upiVpa, setUpiVpa] = useState('');
  const [selectedBank, setSelectedBank] = useState('SBI');
  const [selectedWallet, setSelectedWallet] = useState('Paytm');
  
  // Validation and UI states
  const [errors, setErrors] = useState({});
  const [touched, setTouched] = useState({});
  const [loading, setLoading] = useState(false);
  const [paymentLoading, setPaymentLoading] = useState(false);
  const [errorMsg, setErrorMsg] = useState('');
  const [successMsg, setSuccessMsg] = useState('');
  const [canBook, setCanBook] = useState(true);

  const CylinderPrice = 950.00;

  // Must match booking.refill-gap-minutes in booking-service's application.yml.
  // This is a client-side pre-check only (for instant feedback) — the backend
  // enforces the real rule independently on every booking attempt.
  const REFILL_GAP_MINUTES = 2;

  const formatGapDuration = (minutes) => {
    if (minutes >= 1440) {
      const days = Math.ceil(minutes / 1440);
      return `${days} day${days === 1 ? '' : 's'}`;
    } else if (minutes >= 60) {
      const hours = Math.ceil(minutes / 60);
      return `${hours} hour${hours === 1 ? '' : 's'}`;
    }
    const mins = Math.ceil(minutes);
    return `${mins} minute${mins === 1 ? '' : 's'}`;
  };

  useEffect(() => {
    const checkProfileAndHistory = async () => {
      try {
        const data = await customerService.getProfile();
        setProfile(data);
        if (data.status === 'Suspended') {
          setErrorMsg("Your gas connection has been suspended. Cylinder booking is disabled.");
          setCanBook(false);
          setPageLoading(false);
          return;
        }

        // A customer may only have one active booking at a time — check this
        // before the time-gap policy, mirroring the backend's check order.
        const ACTIVE_STATUSES = ['PendingPayment', 'Paid', 'Assigned', 'OutForDelivery', 'Delivered'];
        const history = await bookingService.getHistory();
        const activeBooking = history.find(b => ACTIVE_STATUSES.includes(b.status));
        if (activeBooking) {
          setErrorMsg(`You already have an active booking (#${activeBooking.id}, status: ${activeBooking.status}). Please wait for it to be delivered and returned before booking another cylinder.`);
          setCanBook(false);
          setPageLoading(false);
          return;
        }

        // Check refill gap policy
        const nonCancelled = history.filter(b => b.status !== 'Cancelled');
        if (nonCancelled.length > 0) {
          const lastBooking = nonCancelled[0]; // Sorted by date desc from backend API
          const lastBookingDate = new Date(lastBooking.bookingDate);
          const currentDate = new Date();
          const diffMinutes = Math.abs(currentDate - lastBookingDate) / (1000 * 60);

          if (diffMinutes < REFILL_GAP_MINUTES) {
            const remainingMinutes = REFILL_GAP_MINUTES - diffMinutes;
            setErrorMsg(`Minimum gap between refills is ${formatGapDuration(REFILL_GAP_MINUTES)}. You can book another cylinder in ${formatGapDuration(remainingMinutes)}.`);
            setCanBook(false);
          }
        }
      } catch (err) {
        console.error("Failed to load profile/history", err);
        if (err.response && err.response.status === 404) {
          setErrorMsg("Please complete your connection profile before booking a cylinder.");
        } else {
          setErrorMsg("Failed to retrieve connection settings. Try again later.");
        }
      } finally {
        setPageLoading(false);
      }
    };
    checkProfileAndHistory();
  }, []);

  // Validate Card Fields
  const validateCard = (name, value) => {
    let error = '';
    if (name === 'cardNumber') {
      if (!value) {
        error = 'Card number is required.';
      } else if (!/^\d{16}$/.test(value.replace(/\s+/g, ''))) {
        error = 'Please enter a valid 16-digit credit card number.';
      }
    } else if (name === 'cardExpiry') {
      if (!value) {
        error = 'Expiry date is required.';
      } else {
        const match = value.match(/^(0[1-9]|1[0-2])\/?([0-9]{2})$/);
        if (!match) {
          error = 'Expiry date must be in MM/YY format.';
        } else {
          const month = parseInt(match[1], 10);
          const year = parseInt(match[2], 10);
          
          const currentDate = new Date();
          const currentMonth = currentDate.getMonth() + 1;
          const currentYear = currentDate.getFullYear() % 100;
          
          if (year < currentYear || (year === currentYear && month < currentMonth)) {
            error = 'Expiry date must be in the future.';
          }
        }
      }
    } else if (name === 'cardCvv') {
      if (!value) {
        error = 'CVV is required.';
      } else if (!/^\d{3}$/.test(value)) {
        error = 'CVV must be exactly 3 digits.';
      }
    }
    return error;
  };

  const handleCardBlur = (e) => {
    const { name, value } = e.target;
    setTouched({ ...touched, [name]: true });
    const err = validateCard(name, value);
    setErrors(prev => ({ ...prev, [name]: err }));
  };

  const handleCardChange = (e) => {
    const { name, value } = e.target;
    if (name === 'cardNumber') setCardNumber(value.replace(/\D/g, '').substring(0, 16));
    if (name === 'cardExpiry') {
      let val = value.replace(/\D/g, '');
      if (val.length >= 2) {
        val = val.substring(0, 2) + '/' + val.substring(2, 4);
      }
      setCardExpiry(val.substring(0, 5));
    }
    if (name === 'cardCvv') setCardCvv(value.replace(/\D/g, '').substring(0, 3));

    if (touched[name]) {
      const err = validateCard(name, value);
      setErrors(prev => ({ ...prev, [name]: err }));
    }
  };

  const handleBookingSubmit = async (e) => {
    e.preventDefault();
    setErrorMsg('');
    setLoading(true);

    try {
      const booking = await bookingService.createBooking(cylinderCount);
      setBookingDetails(booking);
      setShowPaymentModal(true);
      // Reset card inputs
      setCardNumber('');
      setCardExpiry('');
      setCardCvv('');
      setTouched({});
      setErrors({});
    } catch (err) {
      console.error(err);
      setErrorMsg(err.response?.data?.message || 'Cylinder booking failed.');
    } finally {
      setLoading(false);
    }
  };

  const handlePaymentSubmit = async (e) => {
    e.preventDefault();
    setErrorMsg('');

    if (paymentMethod === 'CARD' || paymentMethod === 'DEBIT_CARD') {
      const newTouched = { cardNumber: true, cardExpiry: true, cardCvv: true };
      setTouched(newTouched);

      const cardErr = validateCard('cardNumber', cardNumber);
      const expErr = validateCard('cardExpiry', cardExpiry);
      const cvvErr = validateCard('cardCvv', cardCvv);

      if (cardErr || expErr || cvvErr) {
        setErrors({ cardNumber: cardErr, cardExpiry: expErr, cardCvv: cvvErr });
        return;
      }
    } else if (paymentMethod === 'UPI') {
      if (!/^[\w.\-]{2,}@[a-zA-Z]{2,}$/.test(upiVpa.trim())) {
        setErrorMsg('Please enter a valid UPI ID (e.g. yourname@okhdfcbank).');
        return;
      }
    }
    // NETBANKING and WALLET just need a selection, already defaulted.

    setPaymentLoading(true);
    try {
      // Trigger verify call with mock transaction reference
      const simulatedPaymentId = `pay_sim_${Math.random().toString(36).substring(2, 10).toUpperCase()}`;
      const signature = await computeMockRazorpaySignature(
        bookingDetails.razorpayOrderId,
        simulatedPaymentId
      );
      await paymentService.verifyPayment(
        bookingDetails.id,
        bookingDetails.razorpayOrderId,
        simulatedPaymentId,
        signature,
        paymentMethod
      );
      
      setSuccessMsg(`Payment completed! Booking ID: #${bookingDetails.id} is confirmed.`);
      setShowPaymentModal(false);
      
      setTimeout(() => {
        navigate('/customer/dashboard');
      }, 2000);
    } catch (err) {
      console.error(err);
      const backendErrors = err.response?.data?.errors;
      setErrorMsg(
        (Array.isArray(backendErrors) && backendErrors.join(', ')) ||
        err.response?.data?.message ||
        'Payment verification failed.'
      );
    } finally {
      setPaymentLoading(false);
    }
  };

  if (pageLoading) {
    return (
      <div className="d-flex justify-content-center py-5">
        <div className="spinner-border text-orange" role="status" style={{ color: '#ff5e36' }}>
          <span className="visually-hidden">Loading...</span>
        </div>
      </div>
    );
  }

  const isSuspended = profile && profile.status === 'Suspended';
  const hasNoProfile = !profile;

  return (
    <div className="container py-4 d-flex justify-content-center align-items-center animate-slide-up">
      <div className="glass-panel p-4 p-md-5 w-100" style={{ maxWidth: '580px' }}>
        <h2 className="text-white mb-1">Book Refill Cylinder</h2>
        <p className="text-secondary small border-bottom border-secondary-subtle pb-3 mb-4">Request a new LPG delivery to your service address</p>

        {errorMsg && (
          <div className="alert alert-danger d-flex align-items-center gap-2 border-danger-subtle bg-danger bg-opacity-10 text-danger rounded-3 small p-3 mb-4">
            <i className="bi bi-exclamation-triangle-fill fs-5"></i>
            <div>{errorMsg}</div>
          </div>
        )}

        {successMsg && (
          <div className="alert alert-success d-flex align-items-center gap-2 border-success-subtle bg-success bg-opacity-10 text-success rounded-3 small p-3 mb-4">
            <i className="bi bi-check-circle-fill fs-5"></i>
            <div>{successMsg}</div>
          </div>
        )}

        {hasNoProfile ? (
          <div className="text-center py-4">
            <p className="text-secondary small mb-3">You must complete your connection profile settings first.</p>
            <Link to="/customer/complete-profile" className="btn btn-gradient-primary rounded-pill px-4">
              Complete Profile Setup
            </Link>
          </div>
        ) : isSuspended ? (
          <div className="text-center py-4">
            <p className="text-secondary small">Your account connection is suspended. Booking refills is prohibited.</p>
            <Link to="/customer/dashboard" className="btn btn-outline-light rounded-pill px-4 mt-3">
              Go to Dashboard
            </Link>
          </div>
        ) : (
          <form onSubmit={handleBookingSubmit}>
            {/* Distributor Details read-only */}
            <div className="glass-card p-3 mb-4">
              <span className="text-secondary small d-block">Distributor Agency</span>
              <span className="text-white fw-semibold fs-5">{profile.preferredDistributorName}</span>
              <span className="text-secondary small d-block mt-2">Delivery Address</span>
              <span className="text-white-50 small">{profile.address}, {profile.city}, {profile.state} - {profile.pinCode}</span>
            </div>

            {/* Cylinder Count */}
            <div className="mb-4">
              <label className="form-label form-label-custom" htmlFor="cylinderCount">Cylinder Refills Count</label>
              <div className="d-flex align-items-center gap-3">
                <span className="fs-3 fw-bold text-white px-2">1</span>
                <span className="text-muted small ms-auto">(Exactly 1 cylinder per booking policy)</span>
              </div>
            </div>

            {/* Cost Details */}
            <div className="border-top border-secondary-subtle pt-3 mb-4">
              <div className="d-flex justify-content-between mb-2">
                <span className="text-secondary">Refill Price (x{cylinderCount})</span>
                <span className="text-white">₹ {(CylinderPrice * cylinderCount).toFixed(2)}</span>
              </div>
              <div className="d-flex justify-content-between mb-2">
                <span className="text-secondary">GST & Delivery Charges</span>
                <span className="text-success small fw-semibold">FREE</span>
              </div>
              <hr className="border-secondary-subtle" />
              <div className="d-flex justify-content-between">
                <span className="text-white fw-bold">Total Amount Due</span>
                <span className="text-orange fw-bold fs-4" style={{ color: '#ff5e36' }}>₹ {(CylinderPrice * cylinderCount).toFixed(2)}</span>
              </div>
            </div>

            {/* Submit Button */}
            <button
              type="submit"
              className="btn btn-gradient-primary w-100 rounded-pill py-2.5 display-font fs-5 d-flex align-items-center justify-content-center gap-2"
              disabled={loading || !canBook}
            >
              {loading ? (
                <span className="spinner-border spinner-border-sm" role="status"></span>
              ) : (
                <>
                  <i className="bi bi-cart-check-fill"></i> Proceed to Checkout
                </>
              )}
            </button>
          </form>
        )}
      </div>

      {/* Payment Gateway Mock Modal */}
      {showPaymentModal && bookingDetails && (
        <div className="modal show d-block" tabIndex="-1" style={{ backgroundColor: 'rgba(11, 15, 25, 0.85)', backdropFilter: 'blur(8px)' }}>
          <div className="modal-dialog modal-dialog-centered" style={{ maxWidth: '480px' }}>
            <div className="modal-content glass-panel p-4 border border-secondary border-opacity-30">
              <div className="modal-header border-0 pb-0">
                 <h5 className="modal-title text-white d-flex align-items-center gap-2">
                  <i className="bi bi-shield-fill-check text-success"></i> Razorpay Sandbox Checkout
                </h5>
                <button type="button" className="btn-close" onClick={() => setShowPaymentModal(false)} disabled={paymentLoading}></button>
              </div>
              
              <div className="modal-body text-secondary small py-4">
                <p>Simulated secure checkout for Order: <span className="text-white fw-semibold">{bookingDetails.razorpayOrderId}</span></p>
                <div className="d-flex justify-content-between mb-4 bg-secondary p-3 rounded-3" style={{ backgroundColor: 'rgba(255,255,255,0.02)' }}>
                  <span>Amount to Charge:</span>
                  <span className="text-orange fw-bold" style={{ color: '#ff5e36' }}>₹ {bookingDetails.totalAmount}</span>
                </div>

                {/* Payment method tabs */}
                <div className="d-flex gap-2 mb-4 flex-wrap">
                  {[
                    { key: 'CARD', label: 'Card', icon: 'bi-credit-card-fill' },
                    { key: 'DEBIT_CARD', label: 'Debit Card', icon: 'bi-credit-card-2-front-fill' },
                    { key: 'UPI', label: 'UPI', icon: 'bi-qr-code-scan' },
                    { key: 'NETBANKING', label: 'Netbanking', icon: 'bi-bank' },
                    { key: 'WALLET', label: 'Wallet', icon: 'bi-wallet2' },
                  ].map((m) => (
                    <button
                      key={m.key}
                      type="button"
                      className={`btn btn-sm rounded-pill px-3 ${paymentMethod === m.key ? 'btn-gradient-primary' : 'btn-outline-secondary'}`}
                      onClick={() => setPaymentMethod(m.key)}
                      disabled={paymentLoading}
                    >
                      <i className={`bi ${m.icon} me-1`}></i>{m.label}
                    </button>
                  ))}
                </div>

                <form onSubmit={handlePaymentSubmit}>
                  {(paymentMethod === 'CARD' || paymentMethod === 'DEBIT_CARD') && (
                    <>
                      <div className="mb-3">
                        <label className="form-label form-label-custom" htmlFor="cardNumber">
                          16-Digit {paymentMethod === 'DEBIT_CARD' ? 'Debit' : 'Credit'} Card Number
                        </label>
                        <input
                          id="cardNumber"
                          name="cardNumber"
                          type="text"
                          className={`form-control form-control-custom ${touched.cardNumber && errors.cardNumber ? 'is-invalid-custom' : ''}`}
                          placeholder="4111 2222 3333 4444"
                          value={cardNumber}
                          onChange={handleCardChange}
                          onBlur={handleCardBlur}
                          disabled={paymentLoading}
                        />
                        {touched.cardNumber && errors.cardNumber && (
                          <div className="invalid-feedback-custom">{errors.cardNumber}</div>
                        )}
                      </div>

                      <div className="row g-3 mb-4">
                        <div className="col-6">
                          <label className="form-label form-label-custom" htmlFor="cardExpiry">Expiry Date</label>
                          <input
                            id="cardExpiry"
                            name="cardExpiry"
                            type="text"
                            className={`form-control form-control-custom ${touched.cardExpiry && errors.cardExpiry ? 'is-invalid-custom' : ''}`}
                            placeholder="MM/YY"
                            value={cardExpiry}
                            onChange={handleCardChange}
                            onBlur={handleCardBlur}
                            disabled={paymentLoading}
                          />
                          {touched.cardExpiry && errors.cardExpiry && (
                            <div className="invalid-feedback-custom">{errors.cardExpiry}</div>
                          )}
                        </div>
                        <div className="col-6">
                          <label className="form-label form-label-custom" htmlFor="cardCvv">CVV Code</label>
                          <input
                            id="cardCvv"
                            name="cardCvv"
                            type="password"
                            className={`form-control form-control-custom ${touched.cardCvv && errors.cardCvv ? 'is-invalid-custom' : ''}`}
                            placeholder="123"
                            value={cardCvv}
                            onChange={handleCardChange}
                            onBlur={handleCardBlur}
                            disabled={paymentLoading}
                          />
                          {touched.cardCvv && errors.cardCvv && (
                            <div className="invalid-feedback-custom">{errors.cardCvv}</div>
                          )}
                        </div>
                      </div>
                    </>
                  )}

                  {paymentMethod === 'UPI' && (
                    <div className="mb-4 text-center">
                      <div className="d-inline-block p-3 bg-white rounded-3 mb-3">
                        {/* Static mock QR — this is a payment QR, unrelated to the cylinder-tracking QR feature */}
                        <i className="bi bi-qr-code" style={{ fontSize: '110px', color: '#0b0f19' }}></i>
                      </div>
                      <p className="text-secondary small mb-3">Scan with any UPI app, or enter your UPI ID below</p>
                      <input
                        type="text"
                        className="form-control form-control-custom text-white text-center"
                        placeholder="yourname@okhdfcbank"
                        value={upiVpa}
                        onChange={(e) => setUpiVpa(e.target.value)}
                        disabled={paymentLoading}
                      />
                    </div>
                  )}

                  {paymentMethod === 'NETBANKING' && (
                    <div className="mb-4">
                      <label className="form-label form-label-custom">Select Bank</label>
                      <select
                        className="form-select form-control-custom text-white"
                        value={selectedBank}
                        onChange={(e) => setSelectedBank(e.target.value)}
                        disabled={paymentLoading}
                      >
                        <option value="SBI">State Bank of India</option>
                        <option value="HDFC">HDFC Bank</option>
                        <option value="ICICI">ICICI Bank</option>
                        <option value="AXIS">Axis Bank</option>
                        <option value="PNB">Punjab National Bank</option>
                      </select>
                      <p className="text-muted small mt-2 mb-0">You'll be redirected to your bank's sandbox login (simulated).</p>
                    </div>
                  )}

                  {paymentMethod === 'WALLET' && (
                    <div className="mb-4">
                      <label className="form-label form-label-custom">Select Wallet</label>
                      <select
                        className="form-select form-control-custom text-white"
                        value={selectedWallet}
                        onChange={(e) => setSelectedWallet(e.target.value)}
                        disabled={paymentLoading}
                      >
                        <option value="Paytm">Paytm</option>
                        <option value="PhonePe">PhonePe</option>
                        <option value="AmazonPay">Amazon Pay</option>
                        <option value="MobiKwik">MobiKwik</option>
                      </select>
                    </div>
                  )}

                  <button
                    type="submit"
                    className="btn btn-success w-100 rounded-pill py-2.5 fw-semibold d-flex align-items-center justify-content-center gap-2"
                    disabled={paymentLoading}
                  >
                    {paymentLoading ? (
                      <span className="spinner-border spinner-border-sm" role="status"></span>
                    ) : (
                      <>
                        <i className="bi bi-wallet2"></i> Authorize Mock Payment
                      </>
                    )}
                  </button>
                </form>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default BookCylinder;
