server:
  port: 8083

spring:
  application:
    name: distribution-service
  datasource:
    url: jdbc:mysql://localhost:3306/lpg_distribution?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: cdac
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

cylinder:
  qr-secret: CylinderQrHmacSecretLpgBookingApi987654321
  scan-cooldown-minutes: 5
