spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/lpg_bookings
  rabbitmq:
    host: rabbitmq
    port: 5672

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
